#%%
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormHello.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtWidgets, QtCore
from FormHello import Ui_FormHello

class QmyWidget(QtWidgets.QWidget):
    """"""
    def __init__(self, parent=None):
        super().__init__(parent)  # 调用父类构造函数，创建Qwidget窗体
        self.__ui = Ui_FormHello()
        self.__ui.setupUi(self)  # self是Qwidget窗体，可作为参数传给setupUi()
        self.Lab = "单继承的QmyWidget"
        _translate = QtCore.QCoreApplication.translate
        self.__ui.LabHello.setText(_translate("FormHello", "<html><head/><body><p><span style=\" font-size:36pt;\">单继承的QmyWidget</span></p></body></html>"))

    def setBtnText(self, aText):
        self.__ui.btnclose.setText(aText)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    myWidget = QmyWidget()
    myWidget.show()
    myWidget.setBtnText("间接设置")
    sys.exit(app.exec_())