# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormHello.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormHello(object):
    def setupUi(self, FormHello):
        FormHello.setObjectName("FormHello")
        FormHello.resize(637, 431)
        self.LabHello = QtWidgets.QLabel(FormHello)
        self.LabHello.setGeometry(QtCore.QRect(150, 120, 341, 91))
        self.LabHello.setObjectName("LabHello")
        self.btnclose = QtWidgets.QPushButton(FormHello)
        self.btnclose.setGeometry(QtCore.QRect(410, 310, 113, 32))
        self.btnclose.setObjectName("btnclose")

        self.retranslateUi(FormHello)
        QtCore.QMetaObject.connectSlotsByName(FormHello)

    def retranslateUi(self, FormHello):
        _translate = QtCore.QCoreApplication.translate
        FormHello.setWindowTitle(_translate("FormHello", "Demo2-2"))
        self.LabHello.setText(_translate("FormHello", "<html><head/><body><p><span style=\" font-size:36pt;\">Hello, by UI Designer</span></p></body></html>"))
        self.btnclose.setText(_translate("FormHello", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormHello = QtWidgets.QWidget()
    ui = Ui_FormHello()
    ui.setupUi(FormHello)
    FormHello.show()
    sys.exit(app.exec_())
